### ISSUE TITLE
Waila/TOP integration

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#6]
Integration for _WAILA/HWYLA/what ever else fork or knockoff there currently is_ and _The One Probe_ is required. Machines should output their current contents, energy level, maybe upgrades and/or redstone mode.

I am unsure what features TOP has to offer, but maybe we can make certain information optional/configurable. Discussion for details is appreciated.

- [x] Energy
- [x] Fluids
- [x] Discussion about other features to display
- [x] Test whether Technocracy works the TOP not installed
- [x] Finalize and stabilize the code base for TOP/WAILA including reusing their renderers

**Comment by deftk** [comment]
Simple Waila integration for machines was added.

**Comment by deftk** [comment]
Waila Integration was extended to MultiBlock Structures (tool tips currently only show up if the Controller is hovered).
EnergyMeter from the current GUIs is now rendered at the tool tips.

**Comment by deftk** [comment]
TOP Integration for Machines and MultiBlocks was added (currently just for Energy). Not sure if config stuff must be specially implemented or is already handled by TOP (tests required!)

**Comment by Cydhra** [comment]
Waila- and TOP multi-block-machine support should be merged with machine support: 
Use TCAggregatable to generalize over machines and multi-structures.

TOP integration should be rewritten to use the sync packet generation offered by TCAggregatable instead of manual syncing.

**Comment by Cydhra** [comment]
Placing multiblock structure parts yields an exception by Waila:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:61) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
```

investigation required

**Comment by deftk** [comment]
This issue is not caused by the Waila Integration. It exists, because the method getCapability returns null.

**Comment by deftk** [comment]
Looking at other tile entities in multiblocks than the controller causes another exception in Waila:
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.cydhra.technocracy.foundation.capabilities.fluid.DynamicFluidHandler cannot be cast to java.lang.Void
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: net.cydhra.technocracy.foundation.capabilities.fluid.DynamicFluidHandler cannot be cast to java.lang.Void
	at net.cydhra.technocracy.foundation.tileentity.multiblock.refinery.TileEntityRefineryInput.getCapability(TileEntityRefineryInput.kt:21) ~[TileEntityRefineryInput.class:?]
	at mcp.mobius.waila.addons.capability.HUDHandlerTank.getNBTData(HUDHandlerTank.java:60) ~[HUDHandlerTank.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
```

**Comment by Cydhra** [comment]
Not so fast, github, just because I reference it, I do not mean to close it.

**Comment by deftk** [comment]
> TOP integration should be rewritten to use the sync packet generation offered by TCAggregatable instead of manual syncing.

TOP don't uses NBT tags for sync, so it can't be rewritten.

**Comment by deftk** [comment]
Should TOP and Waila show progress information?

**Comment by tth05** [comment]
Currently TOP automatically creates stuff like energy bars if you provide the corresponding capabilities. This hasn't been noticed until now because all blocks have internal buffers and therefore use components. However if you directly provide a capability without using components 2 bars will be displayed.
This should be fixed, probably by disabling WAILA's default bar or if that isn't possible, some variable that enables or disables the custom bar could be introduced.

**Comment by Cydhra** [comment]
What do you mean? The capability of the component is delegated to the tile entity. For a outer system it is completely opaque how the capabilities are implemented, therefore it does not matter whether we use our component system or just a raw capability.
If TOP displays two bars, this must be connected to the fact, that we add one bar manually to TOP and the other one is generated automatically by TOP when it discovers the capability.
I can't exactly remember: did one of the pull requests already fix this?

**Comment by Cydhra** [comment]
Could not reproduce. The bars are only added once. Delegated bars that refer to the controller are also just displayed once.

**Comment by Cydhra** [comment]
Regarding Finalization:
![grafik](https://user-images.githubusercontent.com/14911966/69759434-68be7180-1162-11ea-858e-341c0b445766.png)

It would be great if we'd change this, so it would just show the item icons, not their names. And instead of a tabular view, display all items in one line with a processing arrow in between, so it is visible which items are input, and which are output.
Technically we could even show processing progress this way, although I am unsure whether this would create too much update-traffic between server and client. Thus we should fill the arrow to 100% and ignore progress for now.

In this example: The cobblestone on the left, an arrow in between and the gravel on the right.

A similar design should be displayed in TOP, because this is ugly:

![grafik](https://user-images.githubusercontent.com/14911966/69759687-03b74b80-1163-11ea-8706-dcac213125dc.png)

Adressed by b624c4d58ece28d3b39d7d8e08b816ae51b145a2

**Comment by Cydhra** [comment]
Not perfect, QA should review this, but it works
